# permissions for end users to edit radeoninstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: radeoninstance-editor-role
rules:
- apiGroups:
  - cache.amd.com
  resources:
  - radeoninstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.amd.com
  resources:
  - radeoninstances/status
  verbs:
  - get
