# permissions for end users to view radeoninstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: radeoninstance-viewer-role
rules:
- apiGroups:
  - cache.amd.com
  resources:
  - radeoninstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.amd.com
  resources:
  - radeoninstances/status
  verbs:
  - get
